openapi: 3.0.0
info:
  version: 3.0.0
  title: Moneris API
  description: Moneris API Platform
  termsOfService: https://www.moneris.com/en/legal/terms-of-use
  contact:
    url: https://api-developer.moneris.com
    email: UnifiedAPI@moneris.com
  license:
    name: Moneris
    url: https://developer.moneris.com/Agreements/Terms%20of%20Use
  x-audience: external-public
servers:
  - url: https://api.moneris.io
    description: Production server (uses live data)
  - url: https://api.sb.moneris.io
    description: Sandbox server (uses test data)
tags:
  - name: Payments
    description: Perform and Manage payments
  - name: Payment Methods
    description: Create and Manage payment methods
  - name: Refunds
    description: Perform and Manage payment refunds
  - name: Validations
    description: Perform and Manage card validations
  - name: Customers
    description: Perform and Manage customers
  - name: 3D Secure
    description: Perform and 3D Secure authentications against payment methods
  - name: Kount
    description: Perform and Manage Kount risk assessment inquiries
paths:
  /payments:
    get:
      summary: List Payments
      description: Returns a paginated list of payments.
      operationId: getPayments
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
    post:
      summary: Create Payment
      description: This operation is used to initiate a Payment.
      operationId: createPayments
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
  /payments/{payment-id}:
    get:
      summary: Retrieve Payment
      description: Retrieve a payment by its payment Id
      operationId: getPayment
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
  /payments/{payment-id}/cancel:
    post:
      summary: Cancel Payment
      description: Cancel a payment. This operation may not be possible if the payment has gone through.
      operationId: cancelPayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
  /payments/{payment-id}/complete:
    post:
      summary: Complete Payment
      description: This will effectively capture a payment that has been authorized.
      operationId: completePayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
  /payment-methods:
    get:
      summary: List payment methods
      description: Retrieves a paginated list of payment methods.
      operationId: getPaymentMethods
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
    post:
      summary: Create Payment Method
      description: Create a Payment Method.
      operationId: createPaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
  /payment-methods/{payment-method-id}:
    get:
      summary: Retrieve Payment Method
      description: Retrieve a Payment Method by Id
      operationId: getPaymentMethod
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
    put:
      summary: Update Payment method
      description: |
        Update payment method referenced by its Id. 
        Certain details may not be updated if the payment method was used in a transaction.
      operationId: updatePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
    delete:
      summary: Delete Payment Method
      description: Deletes a payment method.
      operationId: deletePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
  /refunds:
    get:
      summary: List Refunds
      description: Returns a paginated list of refund operations.
      operationId: getRefunds
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
    post:
      summary: Create Refund
      description: |
        This operation is used to create a Refund. 
        For payment refunds, Payment Id is required while payment method is not required.
        For independent refunds, no payment Id is required, however payment method is required.
      operationId: createRefund
      security:
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
  /refunds/{refund-id}:
    get:
      summary: Retrieve Refund
      description: Retrieve a refund by its Id.
      operationId: getRefundById
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
  /validations:
    description: |
      set up a payment method for future payments. 
      Similar to a payment, but no charge is created.
      Useful when onboarding customers but not charging them right away.
    get:
      summary: List Card Validations
      description: Returns a paginated list of the card validations the were executed.
      operationId: getValidations
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
    post:
      summary: Create Card Validation
      description: Initiate a new Card Validation request.
      operationId: createValidation
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
  /validations/{validation-id}:
    get:
      summary: Retrieve Card Validation.
      description: Retrieve a Card Validation by Id.
      operationId: getValidation
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
  /customers:
    description: |
      This API allows to manage past and recurring customers.
      Very useful when tracking and managing charges belonging to the same customer.
    get:
      summary: List Customers
      description: Returns a paginated list of customers.
      operationId: getCustomers
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
    post:
      summary: Create Customer
      description: This operation is used to created a new customer.
      operationId: createCustomers
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
  /customers/{customer-id}:
    get:
      summary: Retrieve Customer
      description: Retrieve a customer by their Id.
      operationId: getCustomer
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
    put:
      summary: Update Customer
      description: Updates customer's details such as name, address etc...
      operationId: updateCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
    delete:
      summary: Delete Customer
      description: Delete a customer by their Id
      operationId: deleteCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
  /three-d-secure/authentications:
    post:
      summary: Create Authentication
      description: |
        This operation is used to create an Authentication request. 
        The authentication request is used to start the validation process of the card. 
        The result of this request determines whether 3DS is supported by the card and what type of authentication is required.
      operationId: createAuthentication
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
  /three-d-secure/authentications/{authentication-id}:
    get:
      summary: Retrieve Authentication
      description: Retrieve an authentication by its authentication Id
      operationId: getAuthentication
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
  /three-d-secure/authentications/{authentication-id}/lookup:
    post:
      summary: Authentication Value Lookup
      description: The point of the 3-D Secure flow is to verify that the true cardholder is a part of the authorization. The challenge flow is used to present a way of authenticating the cardholder using e.g. OTP or a federated identification method.
      operationId: authenticationValueLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
  /three-d-secure/card-lookups:
    post:
      summary: 3DS Card Lookup
      operationId: cardLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
  /kount-inquiries:
    post:
      summary: Create Kount Inquiry
      operationId: createKountInquiry
      security:
        - OAuth2:
            - kount.write
        - ApiKeyAuth: []
      tags:
        - Kount
    get:
      summary: List Kount Inquiries
      operationId: getKountInquiries
      security:
        - OAuth2:
            - kount.read
        - ApiKeyAuth: []
      tags:
        - Kount
  /kount-inquiries/{kount-inquiry-id}:
    get:
      summary: Get Kount Inquiry by Id
      operationId: getKountInquiryById
      security:
        - OAuth2:
            - kount.read
        - ApiKeyAuth: []
      tags:
        - Kount
  /kount-inquiries/{kount-inquiry-id}/assert:
    post:
      summary: Kount Inquiry Assert
      operationId: kountInquiryAssert
      security:
        - OAuth2:
            - kount.write
        - ApiKeyAuth: []
      tags:
        - Kount
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
      description: |
        An API key is a token that a client provides when making API calls.

        API keys are supposed to be a secret that only the client and server know about.
    OAuth2:
      type: oauth2
      description: |
        OAuth 2.0 is an authorization protocol that gives an API client limited access to user data on a web server.

        OAuth relies on authentication scenarios, that allows the resource owner (user) to share the protected content from the server, hosting the resource, without sharing their credentials. For that purpose, an OAuth 2.0 server issues access tokens that the client applications can use to access protected resources on behalf of the resource owner.

        Moneris recommends the use of OAuth 2.0 as it provides fine grained authorization levels.
      flows:
        clientCredentials:
          tokenUrl: https://api.moneris.io/oauth2/token
          scopes:
            payment.read: Grants read access to payment related APIs
            payment.write: Grants read & write access to payment related APIs
            refund.read: Grants read access to refunds
            refund.write: Grants read & write access to refunds
            customer.read: Grants read access to customer data
            customer.write: Grants read & write access to customer data
            kount.read: Grants read access to Kount inquiries
            kount.write: Grants read & write access to Kount inquiries