{
  "openapi": "3.0.0",
  "info": {
    "version": "2.1.0",
    "title": "Moneris API (FR)",
    "description": "Plateforme des API de Moneris",
    "termsOfService": "https://www.moneris.com/fr-ca/juridiques/conditions-utilisation",
    "contact": {
      "url": "https://api-developer.moneris.com",
      "email": "UnifiedAPI@moneris.com"
    },
    "license": {
      "name": "Moneris",
      "url": "https://developer.moneris.com/Agreements/Terms%20of%20Use"
    },
    "x-audience": "external-public"
  },
  "servers": [
    {
      "url": "https://api.moneris.io",
      "description": "Production server (uses live data)"
    },
    {
      "url": "https://api.sb.moneris.io",
      "description": "Sandbox server (uses test data)"
    }
  ],
  "tags": [
    {
      "name": "Payments",
      "description": "Perform and Manage payments"
    },
    {
      "name": "Payment Methods",
      "description": "Create and Manage payment methods"
    },
    {
      "name": "Refunds",
      "description": "Perform and Manage payment refunds"
    },
    {
      "name": "Validations",
      "description": "Perform and Manage card validations"
    },
    {
      "name": "Customers",
      "description": "Perform and Manage customers"
    },
    {
      "name": "3D Secure",
      "description": "Perform and 3D Secure authentications against payment methods"
    },
    {
      "name": "Kount",
      "description": "Perform and Manage Kount risk assessment inquiries"
    }
  ],
  "paths": {
    "/payments": {
      "get": {
        "summary": "Liste des paiements",
        "description": "Renvoie une liste paginée de paiements.",
        "operationId": "getPayments",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Paiements"
        ]
      },
      "post": {
        "summary": "Créer un paiement",
        "description": "Cette opération est utilisée pour initier un paiement.",
        "operationId": "createPayments",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Paiements"
        ]
      }
    },
    "/payments/{payment-id}": {
      "get": {
        "summary": "Récupérer le paiement",
        "description": "Récupérer un paiement à l’aide de son ID de paiement",
        "operationId": "getPayment",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Paiements"
        ]
      }
    },
    "/payments/{payment-id}/cancel": {
      "post": {
        "summary": "Annuler le paiement",
        "description": "Annuler un paiement. Cette opération peut ne pas être possible si le paiement a été effectué.",
        "operationId": "cancelPayment",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Paiements"
        ]
      }
    },
    "/payments/{payment-id}/complete": {
      "post": {
        "summary": "Effectuer le paiement",
        "description": "Cela permettra de saisir efficacement un paiement qui a été autorisé.",
        "operationId": "completePayment",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Paiements"
        ]
      }
    },
    "/payment-methods": {
      "get": {
        "summary": "Répertorier les modes de paiement",
        "description": "Récupère une liste paginée des modes de paiement.",
        "operationId": "getPaymentMethods",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Modes de Paiement"
        ]
      },
      "post": {
        "summary": "Créer un mode de paiement",
        "description": "Créez un mode de paiement.",
        "operationId": "createPaymentMethod",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Modes de Paiement"
        ]
      }
    },
    "/payment-methods/{payment-method-id}": {
      "get": {
        "summary": "Récupérer le mode de paiement",
        "description": "Récupérer un moyen de paiement par ID",
        "operationId": "getPaymentMethod",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Modes de Paiement"
        ]
      },
      "put": {
        "summary": "Mettre à jour le mode de paiement",
        "description": "Mettre à jour le mode de paiement référencé par son Id. \nCertaines informations peuvent ne pas être mises à jour si le mode de paiement a été utilisé dans une transaction.\n",
        "operationId": "updatePaymentMethod",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Modes de Paiement"
        ]
      },
      "delete": {
        "summary": "Supprimer le mode de paiement",
        "description": "Supprime un mode de paiement.",
        "operationId": "deletePaymentMethod",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Modes de Paiement"
        ]
      }
    },
    "/refunds": {
      "get": {
        "summary": "Liste des remboursements",
        "description": "Renvoie une liste paginée des opérations de remboursement.",
        "operationId": "getRefunds",
        "security": [
          {
            "OAuth2": [
              "refund.read"
            ]
          },
          {
            "OAuth2": [
              "refund.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Remboursements"
        ]
      },
      "post": {
        "summary": "Créer un remboursement",
        "description": "Cette opération est utilisée pour créer un remboursement. \nPour les remboursements de paiement, l’ID de paiement est requis tandis que le mode de paiement n’est pas requis.\nPour les remboursements indépendants, aucun identifiant de paiement n’est requis, mais le mode de paiement est requis.\n",
        "operationId": "createRefund",
        "security": [
          {
            "OAuth2": [
              "refund.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Remboursements"
        ]
      }
    },
    "/refunds/{refund-id}": {
      "get": {
        "summary": "Récupérer le remboursement",
        "description": "Récupérer un remboursement par son Id.",
        "operationId": "getRefundById",
        "security": [
          {
            "OAuth2": [
              "refund.read"
            ]
          },
          {
            "OAuth2": [
              "refund.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Remboursements"
        ]
      }
    },
    "/validations": {
      "description": "Paramétrez un mode de paiement pour les paiements futurs. \nSimilaire à un paiement, mais aucun frais n’est créé.\nUtile lors de l’intégration des clients, mais pas pour les facturer tout de suite.\n",
      "get": {
        "summary": "Validations de cartes de liste",
        "description": "Renvoie une liste paginée des validations de cartes qui ont été exécutées.",
        "operationId": "getValidations",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Validations"
        ]
      },
      "post": {
        "summary": "Créer une validation de carte",
        "description": "Lancez une nouvelle demande de validation de carte.",
        "operationId": "createValidation",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Validations"
        ]
      }
    },
    "/validations/{validation-id}": {
      "get": {
        "summary": "Récupérer la validation de la carte.",
        "description": "Récupérer une validation de carte par id.",
        "operationId": "getValidation",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Validations"
        ]
      }
    },
    "/customers": {
      "description": "Cette API permet de gérer les clients passés et récurrents.\nTrès utile lors du suivi et de la gestion des frais appartenant au même client.\n",
      "get": {
        "summary": "Liste des clients",
        "description": "Renvoie une liste paginée de clients.",
        "operationId": "getCustomers",
        "security": [
          {
            "OAuth2": [
              "customer.read"
            ]
          },
          {
            "OAuth2": [
              "customer.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Clients"
        ]
      },
      "post": {
        "summary": "Créer un client",
        "description": "Cette opération permet de créer un nouveau client.",
        "operationId": "createCustomers",
        "security": [
          {
            "OAuth2": [
              "customer.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Clients"
        ]
      }
    },
    "/customers/{customer-id}": {
      "get": {
        "summary": "Récupérer le client",
        "description": "Récupérer un client par son Id.",
        "operationId": "getCustomer",
        "security": [
          {
            "OAuth2": [
              "customer.read"
            ]
          },
          {
            "OAuth2": [
              "customer.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Clients"
        ]
      },
      "put": {
        "summary": "Mettre à jour le client",
        "description": "Met à jour les données du client telles que le nom, l’adresse, etc.",
        "operationId": "updateCustomer",
        "security": [
          {
            "OAuth2": [
              "customer.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Clients"
        ]
      },
      "delete": {
        "summary": "Supprimer le client",
        "description": "Supprimer un client par son identifiant",
        "operationId": "deleteCustomer",
        "security": [
          {
            "OAuth2": [
              "customer.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Clients"
        ]
      }
    },
    "/three-d-secure/authentications": {
      "post": {
        "summary": "Créer une authentification",
        "description": "Cette opération permet de créer une demande d’authentification. \nLa demande d’authentification sert à lancer le processus de validation de la carte. \nLe résultat de cette demande détermine si 3DS est pris en charge par la carte et quel type d’authentification est requis.\n",
        "operationId": "createAuthentication",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Authentification 3DS"
        ]
      }
    },
    "/three-d-secure/authentications/{authentication-id}": {
      "get": {
        "summary": "Récupérer l’authentification",
        "description": "Récupérer une authentification par son ID d’authentification",
        "operationId": "getAuthentication",
        "security": [
          {
            "OAuth2": [
              "payment.read"
            ]
          },
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Authentification 3DS"
        ]
      }
    },
    "/three-d-secure/authentications/{authentication-id}/lookup": {
      "post": {
        "summary": "Recherche de valeur d’authentification",
        "description": "L’objectif du flux 3-D Secure est de vérifier que le véritable titulaire de la carte fait partie de l’autorisation. Le flux d’authentification est utilisé pour présenter un moyen d’authentifier le titulaire de la carte à l’aide, par exemple, de l’OTP ou d’une méthode d’identification fédérée.",
        "operationId": "authenticationValueLookup",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Authentification 3DS"
        ]
      }
    },
    "/three-d-secure/card-lookups": {
      "post": {
        "summary": "Recherche de carte 3DS",
        "operationId": "cardLookup",
        "security": [
          {
            "OAuth2": [
              "payment.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Authentification 3DS"
        ]
      }
    },
    "/kount-inquiries": {
      "post": {
        "summary": "Créer une demande Kount",
        "operationId": "createKountInquiry",
        "security": [
          {
            "OAuth2": [
              "kount.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Kount"
        ]
      },
      "get": {
        "summary": "Liste Kount Demandes de renseignements",
        "operationId": "getKountInquiries",
        "security": [
          {
            "OAuth2": [
              "kount.read"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Kount"
        ]
      }
    },
    "/kount-inquiries/{kount-inquiry-id}": {
      "get": {
        "summary": "Obtenir Kount Inquiry by Id",
        "operationId": "getKountInquiryById",
        "security": [
          {
            "OAuth2": [
              "kount.read"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Kount"
        ]
      }
    },
    "/kount-inquiries/{kount-inquiry-id}/assert": {
      "post": {
        "summary": "Kount Inquiry Assert",
        "operationId": "kountInquiryAssert",
        "security": [
          {
            "OAuth2": [
              "kount.write"
            ]
          },
          {
            "ApiKeyAuth": []
          }
        ],
        "tags": [
          "Kount"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-Api-Key"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.moneris.io/oauth2/token",
            "scopes": {
              "payment.read": "Grants read access to payment related APIs",
              "payment.write": "Grants read & write access to payment related APIs",
              "refund.read": "Grants read access to refunds",
              "refund.write": "Grants read & write access to refunds",
              "customer.read": "Grants read access to customer data",
              "customer.write": "Grants read & write access to customer data",
              "kount.read": "Grants read access to Kount inquiries",
              "kount.write": "Grants read & write access to Kount inquiries"
            }
          }
        }
      }
    }
  }
}