openapi: 3.0.0
info:
  version: 1.0.1
  title: Moneris API
  x-i18n-title-fr: API de Moneris
  description: |
    Moneris API Platform

    [<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height:32px;">](https://god.gw.postman.com/run-collection/25575461-ab82f3e6-bc3e-471e-bbf5-3875f1616ef9?action=collection%2Ffork&collection-url=entityId%3D25575461-ab82f3e6-bc3e-471e-bbf5-3875f1616ef9%26entityType%3Dcollection%26workspaceId%3D5d2a9a0f-57a7-441c-b2af-fe6315e80a08)
  x-i18n-description-fr: |
    Plateforme des API de Moneris

    [<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height:32px;">](https://god.gw.postman.com/run-collection/25575461-ab82f3e6-bc3e-471e-bbf5-3875f1616ef9?action=collection%2Ffork&collection-url=entityId%3D25575461-ab82f3e6-bc3e-471e-bbf5-3875f1616ef9%26entityType%3Dcollection%26workspaceId%3D5d2a9a0f-57a7-441c-b2af-fe6315e80a08)
  termsOfService: https://www.moneris.com/en/legal/terms-of-use
  x-i18n-termsOfService-fr: https://www.moneris.com/fr-ca/juridiques/conditions-utilisation
  contact:
    x-i18n-name-fr: Support Developpeur Moneris (MonDev)
    url: https://api-developer.moneris.com
    email: UnifiedAPI@moneris.com
  license:
    name: Moneris
    url: https://developer.moneris.com/Agreements/Terms%20of%20Use
  x-audience: external-public
servers:
  - url: https://api.moneris.io
    description: Production server (uses live data)
  - url: https://api.sb.moneris.io
    description: Sandbox server (uses test data)
paths:
  /payments:
    get:
      summary: List Payments
      description: Returns a paginated list of payments.
      operationId: getPayments
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
      x-i18n-tags-fr:
        - Paiements
      x-i18n-summary-fr: Liste des paiements
      x-i18n-description-fr: Renvoie une liste paginée de paiements.
    post:
      summary: Create Payment
      description: This operation is used to initiate a Payment.
      operationId: createPayments
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
      x-i18n-tags-fr:
        - Paiements
      x-i18n-summary-fr: Créer un paiement
      x-i18n-description-fr: Cette opération est utilisée pour initier un paiement.
  /payments/{payment-id}:
    get:
      summary: Retrieve Payment
      description: Retrieve a payment by its payment Id
      operationId: getPayment
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
      x-i18n-tags-fr:
        - Paiements
      x-i18n-summary-fr: Récupérer le paiement
      x-i18n-description-fr: Récupérer un paiement à l’aide de son ID de paiement
  /payments/{payment-id}/cancel:
    post:
      summary: Cancel Payment
      description: Cancel a payment. This operation may not be possible if the payment has gone through.
      operationId: cancelPayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
      x-i18n-tags-fr:
        - Paiements
      x-i18n-summary-fr: Annuler le paiement
      x-i18n-description-fr: Annuler un paiement. Cette opération peut ne pas être possible si le paiement a été effectué.
  /payments/{payment-id}/complete:
    post:
      summary: Complete Payment
      description: This will effectively capture a payment that has been authorized.
      operationId: completePayment
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payments
      x-i18n-tags-fr:
        - Paiements
      x-i18n-summary-fr: Paiement complet
      x-i18n-description-fr: Cela permettra de saisir efficacement un paiement qui a été autorisé.
  /payment-methods:
    get:
      summary: List payment methods
      description: Retrieves a paginated list of payment methods.
      operationId: getPaymentMethods
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
      x-i18n-tags-fr:
        - Modes de paiements
      x-i18n-summary-fr: Répertorier les modes de paiement
      x-i18n-description-fr: Récupère une liste paginée des modes de paiement.
    post:
      summary: Create Payment Method
      description: Create a Payment Method.
      operationId: createPaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
      x-i18n-tags-fr:
        - Modes de paiements
      x-i18n-summary-fr: Créer un mode de paiement
      x-i18n-description-fr: Créez un mode de paiement.
  /payment-methods/{payment-method-id}:
    get:
      summary: Retrieve Payment Method
      description: Retrieve a Payment Method by Id
      operationId: getPaymentMethod
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
      x-i18n-tags-fr:
        - Modes de paiements
      x-i18n-summary-fr: Récupérer le mode de paiement
      x-i18n-description-fr: Récupérer un mode de paiement par ID
    put:
      summary: Update Payment method
      description: |
        Update payment method referenced by its Id. 
        Certain details may not be updated if the payment method was used in a transaction.
      operationId: updatePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
      x-i18n-tags-fr:
        - Modes de paiements
      x-i18n-summary-fr: Mettre à jour le mode de paiement
      x-i18n-description-fr: |
        Mettre à jour le mode de paiement référencé par son Id. 
        Certaines informations peuvent ne pas être mises à jour si le mode de paiement a été utilisé dans une transaction.
    delete:
      summary: Delete Payment Method
      description: Deletes a payment method.
      operationId: deletePaymentMethod
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Payment Methods
      x-i18n-tags-fr:
        - Modes de paiements
      x-i18n-summary-fr: Supprimer le mode de paiement
      x-i18n-description-fr: Supprime un mode de paiement.
  /refunds:
    get:
      summary: List Refunds
      description: Returns a paginated list of refund operations.
      operationId: getRefunds
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
      x-i18n-tags-fr:
        - Remboursements
      x-i18n-summary-fr: Liste des remboursements
      x-i18n-description-fr: Renvoie une liste paginée des opérations de remboursement.
    post:
      summary: Create Refund
      description: |
        This operation is used to create a Refund. 
        For payment refunds, Payment Id is required while payment method is not required.
        For independent refunds, no payment Id is required, however payment method is required.
      operationId: createRefund
      security:
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
      x-i18n-tags-fr:
        - Remboursements
      x-i18n-summary-fr: Créer un remboursement
      x-i18n-description-fr: |
        Cette opération permet de créer un Remboursement. 
        Pour les remboursements de paiement, l’identifiant de paiement est requis tandis que le mode de paiement n’est pas requis.
        Pour les remboursements indépendants, aucun identifiant de paiement n’est requis, mais le mode de paiement est requis.
  /refunds/{refund-id}:
    get:
      summary: Retrieve Refund
      description: Retrieve a refund by its Id.
      operationId: getRefundById
      security:
        - OAuth2:
            - refund.read
        - OAuth2:
            - refund.write
        - ApiKeyAuth: []
      tags:
        - Refunds
      x-i18n-tags-fr:
        - Remboursements
      x-i18n-summary-fr: Récupérer le remboursement
      x-i18n-description-fr: Récupérer un remboursement par son Id.
  /validations:
    description: |
      set up a payment method for future payments. 
      Similar to a payment, but no charge is created.
      Useful when onboarding customers but not charging them right away.
    get:
      summary: List Card Validations
      description: Returns a paginated list of the card validations the were executed.
      operationId: getValidations
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
      x-i18n-tags-fr:
        - Validations
      x-i18n-summary-fr: Validations de cartes de liste
      x-i18n-description-fr: Renvoie une liste paginée des validations de cartes qui ont été exécutées.
    post:
      summary: Create Card Validation
      description: Initiate a new Card Validation request.
      operationId: createValidation
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
      x-i18n-tags-fr:
        - Validations
      x-i18n-summary-fr: Créer une validation de carte
      x-i18n-description-fr: Lancez une nouvelle demande de validation de carte.
    x-i18n-description-fr: |
      Paramétrez un mode de paiement pour les paiements futurs. 
      Similaire à un paiement, mais aucun frais n’est créé.
      Utile lors de l’intégration des clients, mais ne les facturant pas immédiatement.
  /validations/{validation-id}:
    get:
      summary: Retrieve Card Validation.
      description: Retrieve a Card Validation by Id.
      operationId: getValidation
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - Validations
      x-i18n-tags-fr:
        - Validations
      x-i18n-summary-fr: Récupérer la validation de la carte.
      x-i18n-description-fr: Récupérer une validation de carte par id.
  /customers:
    description: |
      This API allows to manage past and recurring customers.
      Very useful when tracking and managing charges belonging to the same customer.
    get:
      summary: List Customers
      description: Returns a paginated list of customers.
      operationId: getCustomers
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
      x-i18n-tags-fr:
        - Clients
      x-i18n-summary-fr: Liste des clients
      x-i18n-description-fr: Renvoie une liste paginée de clients.
    post:
      summary: Create Customer
      description: This operation is used to created a new customer.
      operationId: createCustomers
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
      x-i18n-tags-fr:
        - Clients
      x-i18n-summary-fr: Créer un client
      x-i18n-description-fr: Cette opération permet de créer un nouveau client.
    x-i18n-description-fr: |
      Cette API permet de gérer les clients passés et récurrents.
      Très utile lors du suivi et de la gestion des frais appartenant au même client.
  /customers/{customer-id}:
    get:
      summary: Retrieve Customer
      description: Retrieve a customer by their Id.
      operationId: getCustomer
      security:
        - OAuth2:
            - customer.read
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
      x-i18n-tags-fr:
        - Clients
      x-i18n-summary-fr: Récupérer le client
      x-i18n-description-fr: Récupérer un client par son Id.
    put:
      summary: Update Customer
      description: Updates customer's details such as name, address etc...
      operationId: updateCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
      x-i18n-tags-fr:
        - Clients
      x-i18n-summary-fr: Mettre à jour le client
      x-i18n-description-fr: Met à jour les coordonnées du client telles que le nom, l’adresse, etc.
    delete:
      summary: Delete Customer
      description: Delete a customer by their Id
      operationId: deleteCustomer
      security:
        - OAuth2:
            - customer.write
        - ApiKeyAuth: []
      tags:
        - Customers
      x-i18n-tags-fr:
        - Clients
      x-i18n-summary-fr: Supprimer le client
      x-i18n-description-fr: Supprimer un client par son identifiant
  /three-d-secure:
    post:
      summary: Create Authentication
      description: |
        This operation is used to create an Authentication request. 
        The authentication request is used to start the validation process of the card. 
        The result of this request determines whether 3DS is supported by the card and what type of authentication is required.
      operationId: createAuthentication
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
      x-i18n-tags-fr:
        - 3D Secure
      x-i18n-summary-fr: Créer une authentification
      x-i18n-description-fr: |
        Cette opération permet de créer une demande d’authentification. 
        La demande d’authentification permet de lancer le processus de validation de la carte. 
        Le résultat de cette demande détermine si 3DS est pris en charge par la carte et quel type d’authentification est requis.
  /three-d-secure/{authentication-id}:
    get:
      summary: Retrieve Authentication
      description: Retrieve an authentication by its authentication Id
      operationId: getAuthentication
      security:
        - OAuth2:
            - payment.read
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
      x-i18n-tags-fr:
        - 3D Secure
      x-i18n-summary-fr: Récupérer l’authentification
      x-i18n-description-fr: Récupérer une authentification par son ID d’authentification
  /three-d-secure/{authentication-id}/lookup:
    post:
      summary: Authentication Value Lookup
      description: The point of the 3-D Secure flow is to verify that the true cardholder is a part of the authorization. The challenge flow is used to present a way of authenticating the cardholder using e.g. OTP or a federated identification method.
      operationId: authenticationValueLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
      x-i18n-tags-fr:
        - 3D Secure
      x-i18n-summary-fr: Recherche de valeur d’authentification
      x-i18n-description-fr: L’intérêt du flux 3-D Secure est de vérifier que le véritable titulaire de la carte fait partie de l’autorisation. Le flux de défi est utilisé pour présenter un moyen d’authentifier le titulaire de la carte à l’aide, par exemple, d’un OTP ou d’une méthode d’identification fédérée.
  /three-d-secure/card-lookups:
    post:
      summary: 3DS Card Lookup
      operationId: cardLookup
      security:
        - OAuth2:
            - payment.write
        - ApiKeyAuth: []
      tags:
        - 3D Secure
      x-i18n-tags-fr:
        - 3D Secure
      x-i18n-summary-fr: Recherche de carte 3DS
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.moneris.io/oauth2/token
          scopes:
            payment.read: Grants read access to payment related APIs
            payment.write: Grants read & write access to payment related APIs
            refund.read: Grants read access to refunds
            refund.write: Grants read & write access to refunds
            customer.read: Grants read access to customer data
            customer.write: Grants read & write access to customer data